### ISSUE TITLE
What is GT3 format, which is differences between normal PNG and PNG in GT3 format.

### ISSUE THREAD

**Issue by tntkhang** [SashaCX75/ImageToGTR3#3]
Hi SashaCX75,
Your tools work perfectly when converting image in normal PNG to PNG (GT3) so that I can create, and edit an watch face for GTR3.
But I wonder which is the differences between normal and gt3 format. I'm also google about GT3 format on PNG but found no result.
I am also want to create Java code for converting those things from normal png to gt3 png.
Could you please explain a little bit about it.
Thanks so much.

**Comment by SashaCX75** [comment]
I think these questions are better to ask the developers. I don't know the exact specification of the required image format. 

Through experiments, it was possible to establish that the image format in the clock is most similar to TGA. The image format is slightly different on different models. Unlike TGA, the channel order has been changed. The width of the image must be a multiple of 16, and the actual dimensions of the image are specified in the file header. The alpha channel value cannot be less than any of the color channels (i.e. white cannot have transparency).

**Comment by tntkhang** [comment]
Through your experiments so Amazfit does not have any official document for those things for all contributing developers, right?
I think all watch face creators must use your app to create watch faces.
Big thanks for your experiments sharing, could it be more detail on each or it is a secret:
- Light tga format but different,
- Channel order has been changed
- Width of the image must be a multiple of 16
- Actual dimensions of the image are specified in the file header
- The alpha channel value cannot be less than any of the color channels
I am very appreciative of all your sharing through your experiment, if I am over asking please ignore it. Also big thanks for all your information.

**Comment by SashaCX75** [comment]
It's hard for me to explain in more detail. For tests, I made a file with simple colors (red, blue, green, white, black). I saved one file in tga and packed the second one into a watch face using the Huami online watch face editor. Then I compared files byte by byte in a hex editor.

The utility code is available and you can see for yourself what transformations take place

Posted an updated version of the utility
